lesson04br
vitalyryzhkov/mateAcademy pull request #8
Opened 2019-03-05 16:50 UTC by vitalyryzhkov

2019-03-05 18:31 UTC, Anderwerty requested changes
Resolve comments

2019-03-05 18:31 UTC, Anderwerty commented on src/lesson04/List.java
> +    T get(int i);
Better not `i `but` index`. The same for the rest code.

2019-03-05 18:31 UTC, Anderwerty commented on src/lesson04/List.java
> +    void add(T t);
And not t but item or element

2019-03-05 18:31 UTC, Anderwerty commented on src/lesson04/MyArrayList.java
> +    public int size() {
It is not a size of the list it is capacity.  You should add one more field. For example size. Size= number of elements you put into the list. 
Please read https://habr.com/ru/post/128269/ and reimplement methods

2019-03-05 18:31 UTC, Anderwerty commented on src/lesson04/MyLinkedList.java
> +            size++;
You can see size++ in if and else blocks. So it possible to remove line 30 and  line 35. And put size++ after if-else block.

2019-03-05 18:31 UTC, Anderwerty commented on src/lesson04/MyLinkedList.java
> +        first = last = null;
It is not a java style.  Should be 
first=null;
last=null;

2019-03-05 18:31 UTC, Anderwerty commented on src/lesson04/MyLinkedList.java
> +
Remove redundant blank line.

2019-03-05 18:31 UTC, Anderwerty commented on src/lesson04/MyLinkedList.java
> +    static class Node<E> {
Why no private?

2019-03-05 18:31 UTC, Anderwerty commented on src/lesson04/MyStack.java
> +public class MyStack<T> {
Create interface Stack and implement its methods in the class MyStack

2019-03-05 18:31 UTC, Anderwerty commented on src/lesson04/MyStack.java
> +    private int space;
What is space? Explain, please.

2019-03-06 13:09 UTC, Anderwerty approved these changes

2019-03-06 13:22 UTC, vitalyryzhkov commented on src/lesson04/MyStack.java
> +    private int space;
не смогу объяснить на английском, но это что-то вроде "второго размера" - "объем", скорее всего не очень удачное название, да? лучше capacity?

2019-03-06 13:42 UTC, merged